[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.default]
dependencies = ["build"]

[tasks.build]
description = "Build win64 shellcode then synthapt"
dependencies = ["build-win64", "build-synthapt"]

[tasks.build-win64]
description = "Build win64 shellcode via cargo make"
script_runner = "@shell"
script = '''
cd win64
RUSTUP_TOOLCHAIN=nightly-2024-11-30 cargo make build
'''

[tasks.build-synthapt]
description = "Build synthapt binary (embeds out/shellcode.bin at compile time)"
script_runner = "@shell"
script = '''
cargo build -p synthapt --release
'''

[tasks.build-nix]
description = "Build win64 shellcode then synthapt release binary for Linux/WSL"
dependencies = ["build-win64"]
script_runner = "@shell"
script = '''
cargo build -p synthapt --release
cp target/release/synthapt out/synthapt
'''
