[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.default]
dependencies = ["build"]

[tasks.build]
description = "Build win64 shellcode then synthapt"
dependencies = ["build-win64", "build-synthapt"]

[tasks.build-win64]
description = "Build win64 shellcode via cargo make"
script_runner = "@shell"
script = '''
cd win64
RUSTUP_TOOLCHAIN=nightly cargo make build
'''

[tasks.build-synthapt]
description = "Build synthapt binary (embeds out/shellcode.bin at compile time)"
script_runner = "@shell"
script = '''
cargo build -p synthapt --release
'''

[tasks.build-nix]
description = "Build fully static synthapt binary (requires musl-tools and x86_64-unknown-linux-musl target)"
script_runner = "@shell"
script = '''
cargo build -p synthapt --release --target x86_64-unknown-linux-musl
cp target/x86_64-unknown-linux-musl/release/synthapt out/synthapt
'''
